# Shriven Zenith Master Configuration
# Ultra-Low Latency Trading Platform

[system]
name = "ShrivenZenith"
version = "1.0.0"
environment = "development"  # development | testing | production

[paths]
# All paths can be absolute or relative to the project root
logs_dir = "logs"
cache_dir = "cache"
data_dir = "data"
config_dir = "config"

[logging]
# Logging configuration
enabled = true
level = "INFO"  # DEBUG | INFO | WARN | ERROR | FATAL
file_prefix = "trading"
max_file_size_mb = 100
rotation_count = 10
buffer_size = 16384  # Number of log entries in ring buffer
flush_interval_ms = 100
timestamp_format = "nanoseconds"  # nanoseconds | microseconds | milliseconds

[memory_pool]
# Memory pool configuration
numa_aware = true
numa_node = -1  # -1 for auto-detect
prefault_pages = true
clear_on_allocate = true
clear_on_deallocate = false
statistics_enabled = true
pool_sizes = [
    { name = "orders", block_size = 64, num_blocks = 1048576 },    # 64MB for orders
    { name = "trades", block_size = 32, num_blocks = 524288 },      # 16MB for trades
    { name = "ticks", block_size = 64, num_blocks = 2097152 },      # 128MB for ticks
    { name = "messages", block_size = 256, num_blocks = 65536 }     # 16MB for messages
]

[queue]
# Lock-free queue configuration
spsc_size = 65536
mpmc_size = 16384
cache_line_size = 64
use_memory_barriers = true
busy_wait_iterations = 1000

[threading]
# Thread configuration
cpu_affinity_enabled = true
thread_pool_size = 4
thread_pool_cores = [0, 1, 2, 3]
spinlock_backoff_ns = 10
max_spinlock_iterations = 1000000
use_pause_instruction = true

[networking]
# Network configuration
interface = "eth0"
multicast_ttl = 1
tcp_nodelay = true
tcp_quickack = true
so_busy_poll_us = 50
receive_buffer_size = 4194304  # 4MB
send_buffer_size = 4194304     # 4MB
zero_copy_enabled = false

[performance]
# Performance tuning
huge_pages_enabled = true
cpu_frequency_scaling = "performance"
interrupt_coalescing_us = 100
rdtsc_calibration_enabled = true

[monitoring]
# System monitoring
stats_interval_ms = 1000
metrics_enabled = true
latency_percentiles = [50, 90, 95, 99, 99.9, 99.99]
export_format = "json"  # json | csv | binary

[testing]
# Testing configuration
stress_test_duration_ms = 10000
benchmark_iterations = 1000000
warmup_iterations = 10000
enable_assertions = true
enable_sanitizers = false  # Set to true for debug builds