#pragma once

// Common configuration header
// Generated by CMake from config.h.in

// Version information
#define COMMON_VERSION_MAJOR 1
#define COMMON_VERSION_MINOR 0
#define COMMON_VERSION_PATCH 0
#define COMMON_VERSION_STRING "1.0.0"

// Feature detection
#define HAVE_NUMA TRUE

// Conditional compilation macros
#ifdef HAVE_NUMA
    #define COMMON_NUMA_ENABLED 1
#else
    #define COMMON_NUMA_ENABLED 0
#endif
