#pragma once

// BldgBlocks configuration header
// Generated by CMake from config.h.in

// Version information
#define BLDGBLOCKS_VERSION_MAJOR 1
#define BLDGBLOCKS_VERSION_MINOR 0
#define BLDGBLOCKS_VERSION_PATCH 0
#define BLDGBLOCKS_VERSION_STRING "1.0.0"

// Feature detection
#define HAVE_NUMA TRUE

// Conditional compilation macros
#ifdef HAVE_NUMA
    #define BLDGBLOCKS_NUMA_ENABLED 1
#else
    #define BLDGBLOCKS_NUMA_ENABLED 0
#endif
